### ISSUE TITLE
My portfolio

### ISSUE THREAD

**Issue by Karachristou** [achaljhawar/DevFolio#1]
Hello, I have used your template to create my portfolio. 
Thanks for the template!

here it is https://karachristou.github.io/ 

Please feel free to use anything I made to add to your template if you like. I made a lot of changes and additions. Including adding a script to make the headings highlight dynamically depending on the section you are in.

**Comment by achaljhawar** [comment]
Feel free to commit to the repository all the changes which you have mentioned. And don't forget to share the repo with your colleagues .
