### ISSUE TITLE
Blatant Plagiarism

### ISSUE THREAD

**Issue by sugarfi** [achaljhawar/DevFolio#15]
This is a blatant copy of [this repl.it project](https://repl.it/talk/templates/Portfolio-Site-Template/37272). All of the code was literally copied from that post, with only a minor mention of the original dev in the references. Please take this down ASAP.

**Comment by pieromqwerty** [comment]
+1 Give Lily Credit for her work. The Repl.it team will be filing takedown requests for this repository with Github and Haktoberfest.

**Comment by Codemonkey51** [comment]
+1 Don't steal peoples work and claim it as your own.

**Comment by HahaYes-dev** [comment]
YESSIR

**Comment by HahaYes-dev** [comment]
BIG NO NOES

**Comment by HahaYes-dev** [comment]
WE SHALL GO COMPLETE POG ON THIS POST

**Comment by HahaYes-dev** [comment]
Stealing people's work is what we call plaigarism. Plaigarism is a big no no, and it is not good for whoever actually made this. Tbh, just use open source ethically. Thank you so much.

**Comment by gasparnd** [comment]
Sorry guys but, [Lilly](https://github.com/Lilykhan786) is a big part of this repo. Please read the README for more information. Even so, we will give it the mention it deserves  ❤

**Comment by sugarfi** [comment]
@gasparnd not according to Lily...
