### ISSUE TITLE
Blatant Plaigarism

### ISSUE THREAD

**Issue by HahaYes-dev** [achaljhawar/DevFolio#16]
REE ARE YOU GUYS SERIOUS YOU DON'T STEAL OTHER PEOPLE'S PROJECTS. STEALING IS A BIG NONO, AND YOU DIDN'T EVEN GIVE CREDIT AT ALL. PLEASE DELETE THIS POST, AND IF YOU MADE MONEY OFF OF IT, PLEASE RETURN MONEY BACK.

Thanks,
HahaYes

**Comment by gasparnd** [comment]
WTF
