### ISSUE TITLE
Github Template

### ISSUE THREAD

**Issue by shadowtime2000** [achaljhawar/DevFolio#4]
It would be nice if in the settings of this repository it was set to a Github template so then people could use that feature to create a new repo with the contents of this and have the ability to set the name to their Github pages repo name

**Comment by gasparnd** [comment]
> It would be nice if in the settings of this repository it was set to a Github template so then people could use that feature to create a new repo with the contents of this and have the ability to set the name to their Github pages repo name

Now I'm working in the projects cards, they need love... But your idea is fantastic.
